wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1645176549
    t:
      1:
      - 1
      2:
      - 1
      4: 3.9.7
      5: 0.12.7
      8:
      - 2
      - 3
      - 5
